### ISSUE TITLE
Flatten returns a sequence that is fully evaluated on fetching the first element

### ISSUE THREAD

**Issue by djcsdy** [dtao/lazy.js#129]
```js
var a = Lazy.generate(function (i) {
    console.log("gen a[%d]", i);
    return i;
}, 3);

var b = Lazy.generate(function (i) {
    console.log("gen b[%d]", i);
    return i + 3;
}, 2);

var c = Lazy.generate(function (i) {
    console.log("gen c[%d]", i);
    return i == 0 ? a : b;
}, 2);

var it = c.flatten().getIterator();

it.moveNext();
```

Actual console output:
```txt
gen c[0]
gen a[0]
gen a[1]
gen a[2]
gen c[1]
gen b[0]
gen b[1]
```

Expected console output:
```txt
gen c[0]
gen a[0]
```

**Comment by djcsdy** [comment]
`concat` has the same problem:

```js
var a = Lazy.generate(function (i) {
    console.log("gen a[%d]", i);
    return i;
}, 3);

var b = Lazy.generate(function (i) {
    console.log("gen b[%d]", i);
    return i + 3;
}, 2);

var it = a.concat(b).getIterator();

it.moveNext();
```

Actual console output:
```txt
gen a[0]
gen a[1]
gen a[2]
gen b[0]
gen b[1]
```

Expected console output:
```txt
gen a[0]
```

**Comment by dtao** [comment]
Hey, I see you've been digging in and opening issues over the past couple days—thanks! I really appreciate what you're doing and I plan on addressing a bunch of this stuff very soon.

Just a quick note on this particular observation: the `getIterator` method isn't really the way sequences are supposed to be accessed. I initially introduced it *only* to support async iteration (and [in the docs](http://danieltao.com/lazy.js/docs/#Sequence-getIterator) I indicate it's not supposed to be used). That said, I realize it was my mistake for introducing it, making it public, and not really thinking it through that well.

I bring this up because in some cases `getIterator` causes eager evaluation when `each` actually doesn't. This applies to the two examples you've provided here. In the first case:

```javascript
c.flatten().each(function(e) {
  return false;
});

// outputs:
// gen c[0]
// gen a[0]
```

And in the second:

```javascript
a.concat(b).each(function(e) {
  return false;
});

// outputs:
// gen a[0]
```

So Lazy actually does exhibit the behavior you're expecting, just not when using `getIterator`. In a future version I'll likely make that method "more private", or may remove it entirely.

If there's some reason you really want `getIterator` for scenarios where `each` doesn't cut it, though, let me know.

**Comment by djcsdy** [comment]
Huh! Consider me surprised.

I’m not actually using `getIterator` in my code, I just used it in the examples to demonstrate a problem I thought existed regardless of how you access the sequence. But I see now why I was mistaken.

Sorry for the false negative :-).

**Comment by dtao** [comment]
You're very right to be surprised. I think the most obvious way (and other libraries do this) to accomplish what Lazy does is to use iterators and have `each` be implemented *using* `getIterator`. The reason I haven't taken that approach—though I may reconsider (we're only at 0.4.0, after all)—is that I was able to get better performance by implementing `each` directly for each sequence in terms of its parent's `each`, without the overhead of constructing an intermediate Iterator object.
