### ISSUE TITLE
Add equality fn parameter to uniq()

### ISSUE THREAD

**Issue by olsonpm** [dtao/lazy.js#133]
I understand that key exists, but it just seems most logical to create an equality function parameter.  This way uniqueness doesn't have to be serialized and unnecessarily added as a key instead of the object reference.

I am more than willing to create a PR for this, but wanted to first make sure it's something you guys are okay with.

**Comment by dtao** [comment]
I'm reluctant to do something like this for performance reasons. Without something "key-like", a `uniq` function would need to be implemented in a manner that performs a linear search of existing values for every element. This would perform much worse than the alternative using `keyFn`.

I realize in plenty of cases a dev might understand this trade-off and still prefer the more convenient (?) approach of supplying an equality function. But I'd rather avoid "gotchas" like that if I can.

It seems to me that in almost any case where you could supply an equality function, you could *also* probably figure out a key function that would get the job done just as well. And if the latter would have drastically better performance—like, actually superior complexity, not just de facto devil's-in-the-details performance—well, I'd prefer to be strict and force devs to use that approach.

This brings me back to the extensibility issue. If you as a dev *really* want to specify an equality function instead of a key function, I would certainly like to make it easy for you to do that for yourself. I just don't think I want to put it in the core library.

Thoughts? Does what I've said make sense to you?

**Comment by olsonpm** [comment]
You're right - at first I didn't think performance would be any better because in order to generate a unique key for a class you basically have to serialize it in some fashion.  However now I understand that serialization only has to happen once - thus allowing for future performance benefits.
