### ISSUE TITLE
rename function 'some' into 'any' or add alias

### ISSUE THREAD

**Issue by stasberkov** [dtao/lazy.js#145]
rename function 'some' into 'any'

**Comment by dtao** [comment]
`some` is already aliased as `any`. However, I should update the API docs to indicate that.

**Comment by olsonpm** [comment]
@dtao - Maybe my quick search was bad, but I didn't see any aliases in the API docs.  Is there a way you'd prefer aliases to be documented?  I would create a PR with all the aliases noted properly in the API docs if you told me how you want it to look.  Also, I know there aren't too many, but if you had a list of all of them that would save me some time searching through the code.

The reason I say this is because in the API docs you use '<ObjectLikeSequence>.extend' which is an alias of assign.  Took me a bit to realize that.

**Comment by dtao** [comment]
@olsonpm No, I think listing aliases is simply something I haven't done yet. I can look into adding that.

**Comment by dtao** [comment]
I've updated the doc generation code so that aliases will be included in the 0.4.1 docs. I'll close this issue when I've released the next version.

**Comment by dtao** [comment]
OK, docs updated: http://danieltao.com/lazy.js/docs/
