### ISSUE TITLE
Is this being supported/developed?

### ISSUE THREAD

**Issue by handloomweaver** [dtao/lazy.js#161]
If it isn't can you say why? It's a much needed library but I see no commits in months

**Comment by adrianmc** [comment]
The original author seems to have gone MIA. It'll be up to the community for this to continue. I was also hoping to see this one succeed. Maybe I will try my hand at contributing.

**Comment by pimpedoutgeek** [comment]
There are 165 Forks of this library so if there is a community someone will have to start with some of the Forked versions to try to pull in the better changes.

**Comment by dtao** [comment]
I haven't actively abandoned this project. But I do recognize that I've been neglecting it.

I will try to make some time to go through some open issues over the next few weeks. I've said this before, though—it's just been hard to find that time. So I certainly wouldn't blame anyone for getting exasperated and trying to take development elsewhere. But my *intention*, at least, is to continue development on lazy.js. In other words I'm not "done" with the project.

Another avenue I'd certainly be amenable to would be to open up development by granting write access to some dedicated contributors. Thus far a few people have certainly made some nice contributions but I'm not sure who'd be interested in that.

**Comment by nhduc296** [comment]
I've waiting this project reach to 1.0 :)

**Comment by dtao** [comment]
I just went through and merged all but 1 of the PRs that had been opened over the past year (!) or so. The one remaining is the most substantial so it'll take a bit more time to review.

Today or tomorrow I will do a first pass over the open issues (there are a bunch) and look for low-hanging fruit.

Obviously there's still much to do, but it's a start! I'll release 0.4.1 in the next few days to make these latest changes available.

I'm going to close this issue now because this project is indeed still being developed.
