### ISSUE TITLE
.map()'s second argument contains the element too, instead of the index

### ISSUE THREAD

**Issue by aldipower** [dtao/lazy.js#164]
Given this I expecting the consecutive array index in `i`.

``` javascript
Lazy({key1: "value1", key2: "value2"})
  .keys()
  .map((key, i) => {
    console.log(key, i);
  })
  .value();
```

I am expecting this output:

```
key1 0
key2 1
```

But I am getting also the element in `i`:

```
key1 key1
key2 key2
```

**Comment by juanpaco** [comment]
@aldipower this likely won't help you, but here's the problem in the source, as I can see it.

`Lazy({key1: "value1", key2: "value2"})` produces an `ObjectWrapper`, which has a `keys` function on it (because it uses the an `ObjectLikeSequence` as its prototype).  `keys` produces a `MappedSequence` whose `parent` is the original `ObjectWrapper`.

The `map` call ends up calling `each` on that `MappedSequence`.  Well, `each` on a `MappedSequence` defers to its `parent`'s `each` (https://github.com/dtao/lazy.js/blob/master/lazy.js#L644), and in this case, that `parent` is the original `ObjectWrapper`.  `each` on one of those feeds in the value and the key as the arguments to its iterator function.  So even though `map` is called on the result from `keys`, which I'd expect to iterate like an array, it ends up iterating like an object.

I'm not sure what the solution should be.  Is it correct to assume the sequence returned from `keys` should function like an array and not an object?  I think that is the correct semantics, and so it seems that somewhere between the `keys` call and the `map` call, the jump from object to array has to occur.  Would that be wrapping the return value from `keys` in some other type of conversion sequence?

**Comment by aldipower** [comment]
Hey @juanpaco .
Thank you for your quick analysis! :)
Makes sense, this explains that behavior, which is unexpected to me.

Your suggestion to convert this to an ArraySequence sounds reasonable to me.

In comparison, this works as expected - without lazy.js:

```javascript
Object.keys({key1: "value1", key2: "value2"})
  .map((key, i) => {
    console.log(key, i);
  });
```

And I think this is an unwanted bug, because the lazy.js-documentation itself returns an "array like" sequence:
```javascript
Lazy({ hello: "hola", goodbye: "hasta luego" }).keys() // sequence: ["hello", "goodbye"]
```

**Comment by dtao** [comment]
You're right, this is a bug. It shouldn't be too hard to fix; I'll take a look tomorrow.

**Comment by dtao** [comment]
And by tomorrow I meant "in roughly a year."

Looking now.

**Comment by juanpaco** [comment]
A conversation I've had many times: "I said Tuesday.  I didn't say *which* Tuesday."

Thanks for the fix!

**Comment by dtao** [comment]
I should have timed this better so that I fixed it on Feb 5, 2017.
