### ISSUE TITLE
push and unshift for sequences

### ISSUE THREAD

**Issue by ellismarkf** [dtao/lazy.js#173]
This isn't an issue so much as a question: is there a philosophical reason push and unshift aren't included as sequence methods? Pop and shift are included, and having the counterparts would be very nice, but maybe push and unshift go against the core philosophy of the library, and I'm just not understanding it very well.  Thoughts?

**Comment by jamlen** [comment]
I too would like to understand if there is a reason why these are omitted. I want my library to work with `Sequence`s but without having a `push` method how am I supposed to get extra elements into the Array-like Sequence? Am I just supposed to access the `source` array and `push` on there?

```js
function getStuff() {
  return Lazy([ { a: 1 }, { b: 2 } ]);
}

function moreStuff() {
  var a = getStuff();
  a.push({c: 3});
}
```

**Comment by dtao** [comment]
I suppose I could add `push` and `unshift`. You just need to understand that Lazy sequences aren't (directly) mutable, so by design these methods will return new sequences with the specified value at the tail/head, respectively.

(I say sequences aren't "directly" mutable because they are really more like views; the underlying data _can_ be mutable, and if you modify it directly that will be reflected in the view. But I don't intend to ever put anything on lazy's interface that would allow you to mutate the data underneath.)

**Comment by dtao** [comment]
I've added the methods on the basis that, as you pointed out, pop and shift were already included. So it made sense to me.
