### ISSUE TITLE
Adding Ramda to benchmark comparison

### ISSUE THREAD

**Issue by Risto-Stevcev** [dtao/lazy.js#181]
Are you open to adding Ramda to the benchmark comparison's on the site?
I can submit a pull request adding it to the list.

**Comment by dtao** [comment]
I think I'm going to remove a bunch of the benchmark comparisons because they placed too much emphasis on micro-optimizing cases that in reality all libraries handle totally fine. I might be open to changing up the library comparisons at some point to focus more on the _scalability_ of various library's approaches (which represents the primary motivation for Lazy.js in the first place); and if/when that time comes I'll definitely take a look at Ramda. For now, though, adding more benchmark comparisons is kinda the opposite from the direction I want to be heading.
