### ISSUE TITLE
unable to call get() on result of pairs()

### ISSUE THREAD

**Issue by fenduru** [dtao/lazy.js#192]
``` js
Lazy({ a: 1 }).pairs().toArray()
// [Array[2]]
Lazy({ a: 1 }).pairs().size()
// 1
Lazy({ a: 1 }).pairs().take(1).get(0)
// ["a", 1]
Lazy({ a: 1 }).pairs().get(0)
// undefined
```

**Comment by dtao** [comment]
I don't think I consider this a bug. The result of `pairs` is not array-like, so `get` should not be considered available.

To be honest I'm not sure why the `take(1).get(0)` example works; I'd need to revisit the code to understand that. But regardless I'm going to call this expected behavior.

Let me know if you think I'm overlooking something. (Very possible. It's late and I haven't looked at this library in quite a while.)
