### ISSUE TITLE
Deep clone

### ISSUE THREAD

**Issue by kamleshchandnani** [dtao/lazy.js#202]
I was just going through the docs but didn't find any function for deepclone. Is it intentional?

**Comment by dtao** [comment]
It is intentional in the sense that _deep cloning_ is not really a lazy concept, so I don't think it quite belongs in this library.

With something like Underscore, the idea of cloning makes sense because the basic interface is:

```
object -> object
```

With Lazy.js, it's:

```
object -> sequence
```

So to "deep clone" something wouldn't make sense in the lazy paradigm: you could either lazily produce a *sequence* that includes deep copies of all of an object's properties, in which case it really isn't a *clone* of the object; or you could eagerly produce a deep object copy, in which case you haven't done anything lazily.

Since you were just asking a question, I'm going to close this as I've now answered it. If you'd like to make a feature request, you can create a new ticket for that and we can discuss the merits of the idea there (I am always open to changing my mind).
