### ISSUE TITLE
.length() not a function on a FilteredArrayWrapper

### ISSUE THREAD

**Issue by garygreen** [dtao/lazy.js#204]
Not sure why you can't do this but I would have thought this should work:

```js
Lazy([{ name: 'Gary'}, { name: 'Helen'}, { name: 'Bobby'}])
  .where({ name: 'Helen' })
  .length();

// Result: Uncaught TypeError: Lazy(...).where(...).length is not a function
    at window.onload (VM189:49)
```

However if you convert it to an array it works:

```js
Lazy([{ name: 'Gary'}, { name: 'Helen'}, { name: 'Bobby'}])
  .where({ name: 'Helen' })
  .toArray()
  .length();
```

As `.length()` is an "ultimate" getter and "does" something, wouldn't it make sense to allow calling it rather than having to do `.toArray()` beforehand?

https://jsfiddle.net/5v4d5xtj/

**Comment by dtao** [comment]
It's a fair question, and seems to be pretty much exactly the same question raised in #209.

My current stance on it is that `length()` is not available in scenarios where it would require scanning the entire sequence (such as `FilteredArrayWrapper`) because I'm concerned availability will be mistaken for endorsement and devs will write code like this without realizing how inefficient it is:

```javascript
for (var i = 0; i < seq.length(); i++) {
  doSomething(seq.get(i));
}
```

I'm not 100% attached to this stance; it's just where I stand at the moment. I recognize there might be *some* legitimate cases where you would want to call `length()` knowing that it requires full iteration; but my gut says those cases will be rare and if you're a dev in that situation you can always write your own helper for that purpose.

**Comment by Redsandro** [comment]
I responded in the closed issue: https://github.com/dtao/lazy.js/issues/207#issuecomment-363403526

I did not know that `length` on `Sequence` would require a full scan. In that case, I agree that it should not be available so it will not be mistaken for endorsement.

Perhaps it would be an interesting documentation read to find out how to manually add a `.length()` method to `Sequence`. For devs who ~~need~~ prefer to have it regardless.

**Comment by dtao** [comment]
I could see how it might be worthwhile to document this in more depth.

For now, consider an extreme case. Let's say I have a "database" consisting of a million people in an array and I want to filter down to just those people with the last name "Smith". How many results will the result have? Without some kind of index backing this lookup (e.g. what you'd expect from a *real* database), there is no way to know without actually scanning the data.

Now here's something interesting that I came across just today that I completely forgot about: there is a method available in this library already to eagerly get the count: `size()`. So for devs who really want that, it's there. Note from [the docs](http://danieltao.com/lazy.js/docs/#Sequence-size):

> In some cases, this may require eagerly evaluating the sequence.

This still might change. In hindsight I'm not sure it's better to have two different methods; it might be better to just always make `length()` available if `size()` is there anyway. But for now, this is where we are.

**Comment by Redsandro** [comment]
Thanks for the clarification and reminding us about `size()` @dtao
