### ISSUE TITLE
GroupedSequence - 'slice' method is missing

### ISSUE THREAD

**Issue by x1unix** [dtao/lazy.js#211]
Please add `slice` method from `ArrayLikeSequence`, or better extend `GroupedSequence` from `ArrayLikeSequence` instead of `ObjectSequence` to allow array operations.

**Comment by dtao** [comment]
How would that work? `GroupedSequence` is not "like" an array; it is "like" an object. Its interface inherits from `ObjectLikeSequence` because it makes sense to perform operations on it that you would perform on an object; i.e., getting the value(s) associated with a key. You cannot slice a grouped sequence for the same reason you cannot slice an object.
